global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['web:8000']

  - job_name: 'celery'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['worker:8000']
