# Generated by Django 5.2.3 on 2025-06-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="data",
            field=models.JSONField(
                blank=True,
                help_text="Дополнительные метаданные (JSONB)",
                null=True,
            ),
        ),
    ]
