# Generated by Django 5.2.3 on 2025-06-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0002_transaction_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='data',
            field=models.JSONField(
                blank=True,
                help_text='Дополнительные метаданные (JSON)',
                null=True,
            ),
        ),
    ]
